"""Add user security and verification fields

Revision ID: 0c09e8fa5431
Revises: 
Create Date: 2025-06-19 14:46:59.156382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c09e8fa5431'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thong_ke_thong_bao')
    op.drop_table('cai_dat_thong_bao')
    with op.batch_alter_table('ca_thuc_hanh', schema=None) as batch_op:
        batch_op.alter_column('anh_bia',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('idx_ca_thuc_hanh_ngay')

    with op.batch_alter_table('dang_ky_ca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uu_tien', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('da_xac_nhan', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ngay_xac_nhan', sa.DateTime(), nullable=True))

    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.drop_index('idx_nguoi_dung_vai_tro')
        batch_op.create_index('idx_nguoi_dung_ten_nguoi_dung', ['ten_nguoi_dung'], unique=False)

    with op.batch_alter_table('nhat_ky_hoat_dong', schema=None) as batch_op:
        batch_op.drop_index('idx_nhat_ky_thoi_gian')

    with op.batch_alter_table('thong_bao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nguoi_nhan', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('lien_ket', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('da_doc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ngay_tao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ngay_doc', sa.DateTime(), nullable=True))
        batch_op.alter_column('tieu_de',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'nguoi_dung', ['nguoi_nhan'], ['id'])
        batch_op.drop_column('nguoi_nhan_id')
        batch_op.drop_column('la_broadcast')
        batch_op.drop_column('trang_thai')
        batch_op.drop_column('muc_do_uu_tien')
        batch_op.drop_column('nguoi_gui_id')
        batch_op.drop_column('la_ai_generated')
        batch_op.drop_column('template_id')
        batch_op.drop_column('thoi_gian_doc')
        batch_op.drop_column('du_lieu_template')
        batch_op.drop_column('ml_score')
        batch_op.drop_column('thoi_gian_gui')
        batch_op.drop_column('thoi_gian_nhan')
        batch_op.drop_column('metadata_json')
        batch_op.drop_column('kenh_gui')
        batch_op.drop_column('engagement_score')

    with op.batch_alter_table('vao_ca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diem_so', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nhan_xet_gv', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tep_nop_bai', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('trang_thai_nop', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('thoi_gian_nop', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('vi_tri_ngoi', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vao_ca', schema=None) as batch_op:
        batch_op.drop_column('vi_tri_ngoi')
        batch_op.drop_column('thoi_gian_nop')
        batch_op.drop_column('trang_thai_nop')
        batch_op.drop_column('tep_nop_bai')
        batch_op.drop_column('nhan_xet_gv')
        batch_op.drop_column('diem_so')

    with op.batch_alter_table('thong_bao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engagement_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('kenh_gui', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('metadata_json', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('thoi_gian_nhan', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('thoi_gian_gui', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('ml_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('du_lieu_template', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('thoi_gian_doc', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('template_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('la_ai_generated', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('nguoi_gui_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('muc_do_uu_tien', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('trang_thai', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('la_broadcast', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('nguoi_nhan_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'nguoi_dung', ['nguoi_gui_id'], ['id'])
        batch_op.create_foreign_key(None, 'nguoi_dung', ['nguoi_nhan_id'], ['id'])
        batch_op.alter_column('tieu_de',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('ngay_doc')
        batch_op.drop_column('ngay_tao')
        batch_op.drop_column('da_doc')
        batch_op.drop_column('lien_ket')
        batch_op.drop_column('nguoi_nhan')

    with op.batch_alter_table('nhat_ky_hoat_dong', schema=None) as batch_op:
        batch_op.create_index('idx_nhat_ky_thoi_gian', ['thoi_gian'], unique=False)

    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.drop_index('idx_nguoi_dung_ten_nguoi_dung')
        batch_op.create_index('idx_nguoi_dung_vai_tro', ['vai_tro'], unique=False)

    with op.batch_alter_table('dang_ky_ca', schema=None) as batch_op:
        batch_op.drop_column('ngay_xac_nhan')
        batch_op.drop_column('da_xac_nhan')
        batch_op.drop_column('uu_tien')

    with op.batch_alter_table('ca_thuc_hanh', schema=None) as batch_op:
        batch_op.create_index('idx_ca_thuc_hanh_ngay', ['ngay'], unique=False)
        batch_op.alter_column('anh_bia',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('cai_dat_thong_bao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nguoi_dung_id', sa.INTEGER(), nullable=False),
    sa.Column('cho_phep_web', sa.BOOLEAN(), nullable=True),
    sa.Column('cho_phep_email', sa.BOOLEAN(), nullable=True),
    sa.Column('cho_phep_browser', sa.BOOLEAN(), nullable=True),
    sa.Column('cho_phep_websocket', sa.BOOLEAN(), nullable=True),
    sa.Column('cho_phep_lab_sessions', sa.BOOLEAN(), nullable=True),
    sa.Column('cho_phep_equipment', sa.BOOLEAN(), nullable=True),
    sa.Column('cho_phep_maintenance', sa.BOOLEAN(), nullable=True),
    sa.Column('cho_phep_emergency', sa.BOOLEAN(), nullable=True),
    sa.Column('cho_phep_system', sa.BOOLEAN(), nullable=True),
    sa.Column('cho_phep_marketing', sa.BOOLEAN(), nullable=True),
    sa.Column('cho_phep_ai_suggestions', sa.BOOLEAN(), nullable=True),
    sa.Column('cho_phep_ml_insights', sa.BOOLEAN(), nullable=True),
    sa.Column('cho_phep_predictive_alerts', sa.BOOLEAN(), nullable=True),
    sa.Column('gio_quiet_bat_dau', sa.TIME(), nullable=True),
    sa.Column('gio_quiet_ket_thuc', sa.TIME(), nullable=True),
    sa.Column('so_luong_toi_da_moi_gio', sa.INTEGER(), nullable=True),
    sa.Column('so_luong_toi_da_moi_ngay', sa.INTEGER(), nullable=True),
    sa.Column('ngay_tao', sa.DATETIME(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thong_ke_thong_bao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ngay', sa.DATE(), nullable=False),
    sa.Column('gio', sa.INTEGER(), nullable=False),
    sa.Column('tong_gui', sa.INTEGER(), nullable=True),
    sa.Column('thanh_cong', sa.INTEGER(), nullable=True),
    sa.Column('that_bai', sa.INTEGER(), nullable=True),
    sa.Column('da_doc', sa.INTEGER(), nullable=True),
    sa.Column('info_count', sa.INTEGER(), nullable=True),
    sa.Column('success_count', sa.INTEGER(), nullable=True),
    sa.Column('warning_count', sa.INTEGER(), nullable=True),
    sa.Column('error_count', sa.INTEGER(), nullable=True),
    sa.Column('emergency_count', sa.INTEGER(), nullable=True),
    sa.Column('web_count', sa.INTEGER(), nullable=True),
    sa.Column('email_count', sa.INTEGER(), nullable=True),
    sa.Column('browser_count', sa.INTEGER(), nullable=True),
    sa.Column('websocket_count', sa.INTEGER(), nullable=True),
    sa.Column('thoi_gian_phan_hoi_trung_binh', sa.FLOAT(), nullable=True),
    sa.Column('ty_le_thanh_cong', sa.FLOAT(), nullable=True),
    sa.Column('diem_engagement_trung_binh', sa.FLOAT(), nullable=True),
    sa.Column('ngay_tao', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
